### ISSUE TITLE
Create GPX track for a checklist

### ISSUE THREAD

**Issue by briandfoy** [briandfoy/ebird#2]
Depends on #1 

- [x] extract track for webpage for a checklist
- [x] cache track
- [x] figure out start time and duration
- [x] guess GPS polling interval. Number of point / duration in seconds. Try this across several checklists.
- [ ] create GPX file by assigning the guessed time for each location
- [ ] compare to GPX from Avenza
- [ ] cache the GPX file

**Comment by briandfoy** [comment]
The polling duration does not seem to be even for any track. It increases as the track size increases, so I'm guessing that the track I extract is filtered based on size and not all points are returned.
